title: >
  Programming Language Foundations in Agda

description: >
  Programming Language Foundations in Agda

license: Creative Commons Attribution 4.0 International License
license-file: https://creativecommons.org/licenses/by/4.0/

# To include a new author, add them below in the order in which they are to be
# displayed in the author list. If they have made contributions as an author via
# GitHub, their username MUST be included in the list.
authors:
  - name: Philip Wadler
    email: wadler@inf.ed.ac.uk
    corresponding: true
    github_username: wadler
  - name: Wen Kokke
    email: wen.kokke@ed.ac.uk
    corresponding: true
    github_username: wenkokke
    twitter_username: wenkokke
  - name: Jeremy G. Siek
    email: jsiek@indiana.edu
    corresponding: true
    github_username: jsiek
    twitter_username: jeremysiek

extra_contributors:
  - github_username: cyberglot
  - name: Vikraman Choudhury
  - name: Ben Darwin
  - github_username: koo5
  - name: Anish Tondwalkar
  - name: Nils Anders Danielsson
  - name: Miëtek Bak
  - name: Gergő Érdi
  - name: Adam Sandberg Eriksson
  - name: David Janin
  - name: András Kovács
  - name: Ulf Norell
  - name: Liam O'Connor
  - name: N. Raghavendra
  - name: Roman Kireev
  - name: Amr Sabry

google_analytics: "UA-125055580-1"

repository: plfa/plfa.github.io
branch: dev

baseurl: ""
url: "https://plfa.github.io"
markdown: kramdown
theme: minima
exclude:
  - "hs/"
  - "extra/"
  - "depr/"
  - "papers/"
  - "slides/"
  - "vendor/"
  - "*.agdai"
  - "*.agda-lib"
  - "*.lagda.md"
  - "Guardfile"
  - "Gemfile"
  - "Gemfile.lock"
  - "highlight.sh"
  - "out/epub/acknowledgements.md"
contributors:
- github_username: mdimjasevic
  name: Marko Dimjašević
- github_username: Kwezan
  name: Zbigniew Stanasiuk
- github_username: h4iku
  name: Reza Gharibi
- github_username: ywata
  name: Yasu Watanabe
- github_username: mreed20
  name: Michael Reed
- github_username: Cubesoup
  name: Chad Nester
- github_username: fangyi-zhou
  name: Fangyi Zhou
- github_username: Fingerzam
  name: Juhana Laurinharju
- github_username: momirza
  name: Mo Mirza
- github_username: qaisjp
  name: Qais Patankar
- github_username: kenichi-asai
  name: Kenichi Asai
- github_username: omelkonian
  name: Orestis Melkonian
- github_username: phi16
  name: phi16
- github_username: jonaprieto
  name: Jonathan Prieto
- github_username: abrisan
  name: Alexandru Brisan
- github_username: pedrominicz
  name: Pedro Minicz
- github_username: michel-steuwer
  name: Michel Steuwer
- github_username: caryoscelus
  name: caryoscelus
- github_username: lzmartinico
  name: Lorenzo Martinico
- github_username: whxvd
  name: Sebastian Miele
- github_username: odanoburu
  name: bc²
- github_username: murilogiacometti
  name: Murilo Giacometti Rocha
- github_username: zachrbrown
  name: Zach Brown
- github_username: gallais
  name: G. Allais
- github_username: spwhitt
  name: Spencer Whitt
- github_username: peterthiemann
  name: Peter Thiemann
- github_username: LightAndLight
  name: Isaac Elliott
- github_username: moleike
  name: Alexandre Moreno
- github_username: iblech
  name: Ingo Blechschmidt
- github_username: MatthiasGabriel
  name: Matthias Gabriel
- github_username: AD1024
  name: Mike He
- github_username: trajafri
  name: Syed Turab Ali Jafri
- github_username: Teggy
  name: Torsten Grust
- github_username: zenzike
  name: Nicolas Wu
- github_username: vipo
  name: Slava
- github_username: k4rtik
  name: Kartik Singhal
- github_username: philderbeast
  name: Phil de Joux
- github_username: stepchowfun
  name: Stephan Boyer
- github_username: zgrannan
  name: Zack Grannan
- github_username: navaati
  name: Léo Gillot-Lamure
- github_username: hugomg
  name: Hugo Gualandi
- github_username: kwxm
  name: Kenneth MacKenzie
- github_username: chikeabuah
  name: Chike Abuah
- github_username: L-TChen
  name: Liang-Ting Chen
- github_username: mgttlinger
  name: Merlin Göttlinger
- github_username: laMudri
  name: James Wood
- github_username: citrusmunch
  name: citrusmunch
- github_username: kranich
  name: Stefan Kranich
- github_username: rodamber
  name: Rodrigo Bernardo
- github_username: googleson78
  name: Georgi Lyubenov
- github_username: dalpd
  name: Deniz Alp
- github_username: potato4444
  name: Nathaniel Carroll

